"""Auto-written PARITY.md — action-parity trust receipt for `tether verify`.

Sibling of :mod:`tether.verification_report` (which writes VERIFICATION.md for
`tether validate`'s ONNX-vs-PyTorch numerical round-trip). PARITY.md is the
*behavioral* receipt: it records whether the OPTIMIZED export behaves like the
ORIGINAL native-PyTorch policy when both run the same eval suite, scored through
the Pro 9-gate evaluator.

Called by the `tether verify` CLI handler with the :class:`ParityVerdict`
produced by :func:`tether.verify.run_verify`.
"""
from __future__ import annotations

import platform
import time
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tether.verify import ParityVerdict

REPORT_FILENAME = "PARITY.md"


def _tether_version() -> str:
    try:
        from tether import __version__

        return __version__
    except Exception:
        return "unknown"


def _pct(x: float) -> str:
    return f"{100.0 * x:.1f}%"


def render_parity_report(verdict: "ParityVerdict") -> str:
    """Render the PARITY.md body for ``verdict`` as a markdown string.

    Pure (no I/O) so it can be unit-tested + reused by callers that want the
    text without writing a file.
    """
    from tether.pro.eval_gate import MIN_EPISODES_TO_EVALUATE

    report = verdict.eval_report
    verdict_str = "PASS" if verdict.passed else "FAIL"
    now = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())

    lines: list[str] = [
        "# Tether Action-Parity Verification",
        "",
        f"Generated: {now}",
        "",
        f"**Verdict: {verdict_str}**",
        "",
        "## What this checks",
        "",
        "Does the OPTIMIZED export behave like the ORIGINAL native-PyTorch "
        "policy? Both run the same eval suite, paired by task + seed; the "
        "paired outcomes are scored through the Tether Pro 9-gate evaluator "
        "(original = baseline, optimized = candidate).",
        "",
        "## Run",
        "",
        f"- **Optimized (under test):** `{verdict.optimized_ref}`",
        f"- **Original (reference):** `{verdict.original_ref}`",
        f"- **Suite:** {verdict.suite}",
        f"- **Target:** {verdict.target}",
        f"- **Paired episodes:** {verdict.n_episodes} "
        f"(min for statistical power: {MIN_EPISODES_TO_EVALUATE})",
        f"- **Tether version:** {_tether_version()}",
        f"- **Platform:** {platform.platform()}",
        "",
        "## Headline",
        "",
        "| Metric | Original | Optimized | Delta |",
        "|---|---|---|---|",
        f"| Success rate | {_pct(verdict.original_success_rate)} | "
        f"{_pct(verdict.optimized_success_rate)} | "
        f"{verdict.success_rate_delta * 100:+.1f}pp |",
        "",
    ]

    if verdict.first_failing_gate_id is not None and report.first_failing_gate:
        g = report.first_failing_gate
        lines += [
            f"**First failing gate:** `{g.gate_id}` ({g.gate_class}) — {g.message}",
            "",
        ]

    lines += [
        "## Gate detail",
        "",
        "| Gate | Class | Result | Measured | Threshold | Detail |",
        "|---|---|---|---|---|---|",
    ]
    for g in report.all_gates:
        lines.append(
            f"| {g.gate_id} | {g.gate_class} | "
            f"{'PASS' if g.passed else 'FAIL'} | "
            f"{g.measured:.4g} | {g.threshold:.4g} | {g.message} |"
        )

    lines += [
        "",
        "## v0 scope (read this)",
        "",
        "This is the **v0** parity gate. It reuses the shipped Pro 9-gate "
        "evaluator and the proven LIBERO rollout loop. The load-bearing v0 "
        "signal is **success-rate parity** (gates S3 / P1 / P5: per-task "
        "success-cliff + Wilson confidence intervals).",
        "",
        "The distributional gates (S2 velocity-Wasserstein, P4 action-cosine) "
        "and the latency/memory gates (P2 / P3) currently pass on documented "
        "sentinels because the rollout primitive does not yet surface per-step "
        "action chunks, per-joint velocities, latency, or memory. They are NOT "
        "silently degraded — they are explicitly marked here. The follow-up "
        "distributional engine (MMD / energy-distance two-sample tests) and "
        "embodied metrics (jerk, completion-time, motion-energy) slot in at the "
        "`TODO(tether-verify)` anchors in `src/tether/verify.py`.",
        "",
        "_Auto-generated by `tether verify`. Re-run to refresh this file._",
        "",
    ]
    return "\n".join(lines)


def write_parity_report(
    output_dir: str | Path,
    verdict: "ParityVerdict",
) -> Path:
    """Write ``<output_dir>/PARITY.md`` for ``verdict`` and return its path.

    ``output_dir`` is created if missing (it may be an export dir or a
    dedicated verify-output dir).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / REPORT_FILENAME
    out.write_text(render_parity_report(verdict) + "\n")
    return out


__all__ = ["REPORT_FILENAME", "render_parity_report", "write_parity_report"]
